
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elastic-test
    environment:
      - node.name=elastic-test
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

    networks:
      - sg-net

  kibana:
    build:
      context: .
      dockerfile: Dockerfile.kibana
    container_name: kibana-test
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - SERVER_NAME=kibana-test
      - XPACK_SECURITY_ENABLED=false
      - searchguard.multitenancy.enabled=true

    depends_on:
      - elasticsearch

    ports:
      - 5601:5601
    networks:
      - sg-net
networks:
  sg-net:
    driver: bridge
    
