########################################
# Paramètres de base du cluster
########################################
cluster.name: "docker-cluster"
node.name: "elastic-test"
discovery.type: "single-node"
# On désactive X-Pack Security, puisqu’on utilise Search Guard
xpack.security.enabled: false

########################################
# Ressources et réseau
########################################
bootstrap.memory_lock: true
network.host: 0.0.0.0

########################################
# Search Guard : SSL transport
########################################
searchguard.ssl.transport.enabled: true

# Chemin des certificats (PEM) pour le transport, copiés dans config/certs/
searchguard.ssl.transport.pemcert_filepath: certs/node.pem
searchguard.ssl.transport.pemkey_filepath: certs/node-key.pem
searchguard.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
searchguard.authcz.admin_dn:
  - "EMAILADDRESS=davidkalalak@gmail.com,CN=Altaru,OU=KinEco,O=KinEco,L=Bures,ST=Paris,C=FR"

# (Optionnel) mot de passe de la clé privée
searchguard.ssl.transport.pemkey_password: "altaru"

# (Optionnel) si vous ne voulez pas vérifier l’hostname en single-node
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false

# Désactivation (optionnelle) de TLS sur l'HTTP si vous ne l’utilisez pas pour Kibana
searchguard.ssl.http.enabled: false