_sg_meta:
  type: "config"
  config_version: 2
sg_config:
  dynamic:
    http:
      # Authentification anonyme
      anonymous_auth_enabled: false

      # X-Forwarded-For
      xff:
        enabled: false

    # Paramètres Kibana / multi-tenant
    kibana:
      multitenancy_enabled: true
      server_username: "kibanaserver"
      index: ".kibana"

    # Domaines d'authentification
    authc:
      basic_internal_auth_domain:
        description: "Basic internal authentication"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal

