searchguard:
  ssl:
    transport:
      enabled: true
      pemcert_filepath: certs/node.pem
      pemkey_filepath: certs/node-key.pem
      pemtrustedcas_filepath: certs/root-ca.pem
      # Si votre clé est protégée par un mot de passe, le mettre ici :
      pemkey_password: "altaru"
    # http:
    #   enabled: false  # si vous ne chiffriez pas l'HTTP, sinon vous pouvez l'activer

  allow_unsafe_democertificates: false
  allow_default_init_sgindex: true  # pour un test local
  searchguard.ssl.transport.enabled: true
  searchguard.ssl.transport.pemcert_filepath: certs/node.pem
  searchguard.ssl.transport.pemkey_filepath: certs/node-key.pem
  searchguard.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
  dynamic:
  
    # Liste les ordres d'authentification possibles
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false

    # Authentification par login/password interne (fichiers sg_internal_users.yml)
    authc:
      basic_internal_auth_domain:
        description: "Basic internal authentication"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal

    # Autorisation
    #authz:
      #roles_from_myldap:
        # Exemple si vous utilisiez LDAP, sinon vous pouvez supprimer
       # http_enabled: false
       # transport_enabled: false
       # authorization_backend:
        #  type: ldap

    # Paramètres Kibana / REST API
    kibana:
      multitenancy_enabled: true
      server_username: "kibanaserver"  # un user technique si besoin
      index: ".kibana"

    


