_sg_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "$2y$12$k5t1yZl17ClHzG3HCHS54e4r.crpn/T0NK8HLWFZ8yfEz13Fk3PyK"
  search_guard_roles:
    - "sg_all_access"
  reserved: false
  hidden: false

user_grid:
  hash: "$2y$12$k5t1yZl17ClHzG3HCHS54e4r.crpn/T0NK8HLWFZ8yfEz13Fk3PyK"
  search_guard_roles:
    - "sg_role_grid"
  reserved: false
  hidden: false

user_egf:
  hash: "$2y$12$k5t1yZl17ClHzG3HCHS54e4r.crpn/T0NK8HLWFZ8yfEz13Fk3PyK"
  search_guard_roles:
    - "sg_role_egf"
  reserved: false
  hidden: false
