_sg_meta:
  type: "roles"
  config_version: 2

sg_role_grid:
  cluster_permissions:
    - "CLUSTER_MONITOR"
  index_permissions:
    - index_patterns:
      - "logs-marketing-*"
      allowed_actions:
      - "READ"
  tenant_permissions:
    - tenant_patterns:
      - "grid_tenant"
      allowed_actions:
      - "SGS_KIBANA_ALL_WRITE"

sg_role_egf:
  cluster_permissions:
    - "CLUSTER_MONITOR"
  index_permissions:
    - index_patterns:
      - "logs-marketing-*"
      allowed_actions:
      - "READ"
  tenant_permissions:
    - tenant_patterns:
      - "egf_tenant"
      allowed_actions:
      - "SGS_KIBANA_ALL_WRITE"
      
sg_all_access:
  cluster_permissions:
    - "CLUSTER_ALL"
  index_permissions:
    - index_patterns:
      - "*"
      allowed_actions:
      - "UNLIMITED"
  tenant_permissions:
    - tenant_patterns:
      - "admin_tenant"
      allowed_actions:
      - "SGS_KIBANA_ALL_WRITE"  