_sg_meta:
  type: "tenants"
  config_version: 2

admin_tenant:
  reserved: false
  hidden: false
  description: "Kibana tenant pour administrateur"

grid_tenant:
  reserved: false
  hidden: false
  description: "Kibana tenant pour équipe Grid"

egf_tenant:
  reserved: false
  hidden: false
  description: "Kibana tenant pour équipe EGF"
